version: "2.1"

services:
  oereb-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      oereb-db:
        condition: service_healthy
    environment:
      PGHOST: ${PGHOST:-oereb-db}
      PGPORT: ${PGPORT:-5432}
      PGUSER: ${PGUSER:-postgres}
      PGPASSWORD: ${PGPASSWORD:-postgres}
      PYRAMID_OEREB_PORT: ${PYRAMID_OEREB_PORT:-6543}
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    ports:
      - ${PYRAMID_OEREB_PORT:-6543}:${PYRAMID_OEREB_PORT:-6543}
    networks:
      - default
      - print-network

  oereb-db:
    image: postgis/postgis
    restart: unless-stopped
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PGDATABASE:-pyramid_oereb_test}
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
      PGUSER: ${PGUSER:-postgres}
      PGPORT: ${PGPORT:-5432}
      PGPASSWORD: ${PGPASSWORD:-postgres}
    ports:
      - 15432:${PGPORT:-5432}

networks:
  print-network:
    external: true
