version: '2.1'

x-pg_user: &pg_user
  "postgres"
x-pg_host: &pg_host
  "oereb-db"
x-pg_password: &pg_password
  "postgres"
x-pg_database: &pg_database
  "pyramid_oereb_test"

services:
  oereb-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PGHOST: *pg_host
      PGUSER: *pg_user
      PGPASSWORD: *pg_password
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    ports:
    - 6543:6543
    networks:
      - default
      - print-network

  oereb-db:
    image: postgis/postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: *pg_database
      POSTGRES_USER: *pg_user
      POSTGRES_PASSWORD: *pg_password
      PGPASSWORD: *pg_password
      PGHOST: *pg_host

networks:
  print-network:
    external: true
