name: CI
on: [push]

jobs:

  lint:
    name: Check style (lint)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo rm /etc/apt/sources.list.d/*.list
      - run: sudo apt update
      - run: sudo apt-get install virtualenv libpq-dev libgeos-dev
      - name: Run make lint
        run: make lint
  
  gitattributes:
    name: Check style (git-attributes)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo rm /etc/apt/sources.list.d/*.list
      - run: sudo apt update
      - run: sudo apt-get install virtualenv libpq-dev libgeos-dev
      - name: Run make git-attributes
        run: make git-attributes

  doc:
    name: Make and deploy documentation
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo rm /etc/apt/sources.list.d/*.list
      - run: sudo apt update
      - name: Make documentation
        run: |
          sudo apt-get install virtualenv libpq-dev libgeos-dev
          make doc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: doc/build/html # The folder the action should deploy.

